### ISSUE TITLE
about visualization

### ISSUE THREAD

**Issue by longmalongma** [nihalsid/ViewAL#5]
Hello,can you provide the visualization of segmentation on scannet dataset?

**Comment by nihalsid** [comment]
Hey, do you want code for visualization or some sample visualizations?

**Comment by longmalongma** [comment]
> Hey, do you want code for visualization or some sample visualizations?

Thank you for your reply,I mean the visualization of segmentation result,how to generate .ply files and meshlab can open it.

**Comment by nihalsid** [comment]
The segmentations produced here are 2D, i.e. images. The task for active learning is 2D semantic segmentation, not 3D. Sorry!
