### ISSUE TITLE
Feature Dimension for Coreset and Max representativeness

### ISSUE THREAD

**Issue by nkalavak** [nihalsid/ViewAL#6]
Thanks for sharing your work on improved active selection strategies. I had a question about the choice for feature dims in the Coreset and Max Repr techniques. Is 2432 an arbitrary choice for the different data sets you are evaluating on or was there detailed reasoning behind it that I am missing?

**Comment by nihalsid** [comment]
Hey! Yeah this choice was pretty much arbitrary. I tried just a few other dims.
